version: '3.7'

services:

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${NGINX_CONTAINER}
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./application:/app
      - ./runtime/nginx:/var/log/nginx
    restart: always

  php:
    image: ${PHP_IMAGE_NAME}
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${PHP_CONTAINER}
    environment:
      XDEBUG_CONFIG: 'idekey=${PHPSTORM_IDE_KEY}'
      PHP_IDE_CONFIG: 'serverName=${PHPSTORM_SERVER_NAME}'
    volumes:
      - ./application:/app
    restart: always
