version: '3.7'

services:

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${NGINX_CONTAINER}
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_PORT_SSL}:443
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./application:/app
      - ./runtime/nginx:/var/log/nginx
    networks:
      - development
    restart: always

  php:
    image: ${PHP_IMAGE_NAME}
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${PHP_CONTAINER}
    environment:
      XDEBUG_CONFIG: 'idekey=${PHPSTORM_IDE_KEY}'
      PHP_IDE_CONFIG: 'serverName=${PHPSTORM_SERVER_NAME}'
    volumes:
      - ./application:/app
    networks:
      - development
    restart: always

  mysql:
    image: ${MYSQL_IMAGE}
    container_name: ${MYSQL_CONTAINER}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./runtime/mysql/data:/var/lib/mysql
    networks:
      - development
    restart: always

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./runtime/postgres/data:/var/lib/postgresql/data
    networks:
      - development
    restart: always

  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: ${MONGO_CONTAINER}
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./docker/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./runtime/mongo/data:/data/db
    networks:
      - development
    restart: always

networks:
  development:
    name: ${NETWORK_NAME}